##
## Makefile for Makefile in /home/leblic_c//Documents/lib_my_c
## 
## Made by cesar leblic
## Login   <leblic_c@epitech.net>
## 
## Started on  Mon Mar 26 08:47:14 2012 cesar leblic
## Last update Thu Mar 29 14:45:46 2012 cesar leblic
##

NAME=	stdarg

SRC=	main.c

all:
		cc $(SRC) -o$(NAME) -L. -lmy -I.